### ISSUE TITLE
Save editor crashes after "recognizing" about 40 games

### ISSUE THREAD

**Issue by DioVento** [BernardoGiordano/Checkpoint#1]
As it scans for games and presents icons during intial startup, the app unceremoniously crashes when it gets to around 40 titles. Only twice did a Luma3DS crash dump (https://my.mixtape.moe/dgpgbp.dmp) occur out of the 8 times I tried to use this app, the other times just returned me to the System Menu.

![imag0248](https://user-images.githubusercontent.com/32431626/31054162-acf8d12e-a661-11e7-9ec0-9bca28a2e65c.jpg) 

Manually exiting the app using the Home button caused it to stop adding icons to the screen for at least three minutes, and required a hard reset of the 3DS.

My system version is 11.2.0-35U, I am on a New 3DS. I'm running B9S and Luma v8.1.1.

**Comment by BernardoGiordano** [comment]
Can you send me a list of the titles you have installed?

**Comment by epiccelt** [comment]
Having the same crash. It happens after exactly 50 folders have been created in sd:/Checkpoint/saves/

https://www.dropbox.com/s/9ua5s50l9jirtnl/crash_dump_00000023.dmp?dl=0

**Comment by BernardoGiordano** [comment]
Try this build. https://www.dropbox.com/s/mx0xr8cweeehkih/Checkpoint.cia?dl=0

**Comment by Brawl345** [comment]
v1.0.0 also crashes for me, v1.0.1 works fine - list is populated and all titles are shown, but I get these errors:

```
Error C82044BE
Failed to create backup directory

Error C8804478
Couldn't retrieve the directory list for the title Super Smash Bros

Error C8804478
Couldn't retrieve the extdata list for the title Super Smash Bros.

Error C82044BE
Failed to create backup directory

Error C8804478
Couldn't retrieve the directory list for the title BOXBOXBOY
```
"New" is then hidden for these titles, creating a backup nevertheless throws this error: 
```
Error C8804478
Failed to create destination directory
```

**Comment by BernardoGiordano** [comment]
I'll send a new build later trying to fix this error

**Comment by BernardoGiordano** [comment]
Please let me know with this https://www.dropbox.com/s/mx0xr8cweeehkih/Checkpoint.cia?dl=0

**Comment by Brawl345** [comment]
No error pop-ups with this version and backupping up works (tested Sm4sh save and extdata). Haven't tried restoring, but files seem to be correct, they are the same when backupped up with JKSM. What I noticed is that the folder names changed ("0x00EE0 Super Smash Bros." instead of just "Super Smash Bros."). Is this correct?

**Comment by BernardoGiordano** [comment]
Yes, the folder name change is explained in this commit: https://github.com/BernardoGiordano/Checkpoint/commit/2bab017f9ea5417c41b31b490b3c2bf026f34588 .

Anyways, I'm unsure about extdata restoring, but at least this issue seems to be fixed. Waiting for a feedback from the OP too

**Comment by SuperOkazaki** [comment]
Just wanted to chime in and say that this version works perfectly. I was having the same issue and now it works flawlessly. Thanks!

**Comment by DioVento** [comment]
v1.1 fixed the crash, but the app still doesn't list all my installed titles. At first, I thought it might be auto-excluding files that don't have save data generated, but it's missing some (like Animal Crossing: New Leaf) that do have save data.

**Comment by BernardoGiordano** [comment]
If the app ignores it, it means that the save archive isn't accessible
