### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by CecilFF4** [BernardoGiordano/Checkpoint#10]
To be on par with JKSM, or better, the app could use:

1. Batch backup/restore.
2. Play coin setter.
3. Save data browser, like what FBI has (click on browse, see/interact with contents of save).
4. Option to load icon cache or not, in order to decrease load time further.
5. Theming.
6. "Paper Mario Sticker Star" save export issue (present in JKSM, too). It just errors out when trying to dump the 3rd save slot if that slot is empty.

The app has potential. Would really like to see where this goes.

**Comment by CecilFF4** [comment]
Thank you for adding support for items 1 and 6. After testing the latest version (2.0.0) it seems pretty good. But it still doesn't compare to the speed of using a cache like JKSM. Is it possible to use one at all in your program? That's the feature I would like to see more than anything.

**Comment by BernardoGiordano** [comment]
2 is not a priority

3 is unintuitive and doesn't fit at all with the purpose of the program

4 may be researched but loading time has been decreased **a lot** with the last commits

5 no, if people want different colors they could compile their own version instead, the program is open source
