### ISSUE TITLE
Some bug on latest release

### ISSUE THREAD

**Issue by Volcah** [BernardoGiordano/Checkpoint#101]
* [ ] Issue with Checkpoint for 3DS
* [x] Issue with Checkpoint for Switch
* [ ] Feature request

### Error details

* Entrypoint: Hekate 5.x
* System version: 5.1.0
* Checkpoint version: 3.3.0
* Expected behaviour: Load pages correctly for every user
* Encountered behavior: 
1) If I played some games on a profile, but I switch to another profile which has no savedata for that game, Checkpoint will not recognize the game but the game is still selected
2) If I have more "pages" on a profile, I go to another page, and then I switch to a profile that does not have the same amount of pages as the first profile, Checkpoint freezes
* Result code (if available):
* Steps to reproduce:
  * Launch RCM
  * Launch Hekate 5.x
  * Open HBL
  * Open Checkpoint

1)
  * Select an user that has less displayed games than another
  * Count how many games it displays
  * Select an user that has at least the same number of games + 1 (on the same page)
  * Select the (number of games of the first profile + at least 1) square
  * Go back to the user which has less games
  * (Screenshot below)

2)
  * Select an user that has less pages than another
  * Count how many pages it has
  * Select an user that has at least the same number of pages + 1
  * Go to page (number of pages of the first profile + at least 1)
  * Go back to the user which has less pages
  * Checkpoint freezes (I can't provide a screenshot for that)

![checkpoint_bug](https://user-images.githubusercontent.com/22454917/41321509-92b0da76-6ea4-11e8-9474-514f9d846ce6.png)

For the title: I don't actually know if these bugs were introduced by latest commits but they are only present in this version of Checkpoint

**Comment by BernardoGiordano** [comment]
Does this work? https://www.dropbox.com/s/63cuarl6jou2eh9/Checkpoint.nro?dl=0

**Comment by RyanmFisher** [comment]
Appears that fixed it

**Comment by Volcah** [comment]
Yes, this fixed the problem(s)!
