### ISSUE TITLE
Feature request  Delete all saves but latest (count) save

### ISSUE THREAD

**Issue by fennectech** [BernardoGiordano/Checkpoint#103]
### Feature request details

* I Would like to be able to delete all backups but the last x backups with one click so I could tell it to delete all but the last one or two backups.    
* Because... It would make it more convenient rather than just deleting all saves from NXshell then doing the backup.

**Comment by BernardoGiordano** [comment]
You just press X from checkpoint to delete the currently selected backup, and it takes nothing to do so

**Comment by fennectech** [comment]
I mean all but the current backup in one button press 
  So lets say you have 6 backups for each game.  You press the button (and confirm the deletion) and now you only have the latest save for each game.

**Comment by BernardoGiordano** [comment]
The logic behind 'the latest save' is confusing and will not be the same for everyone. I'm not implementing this
