### ISSUE TITLE
Small glitch in 3.3.0 

### ISSUE THREAD

**Issue by RyanmFisher** [BernardoGiordano/Checkpoint#107]
## Issue template

Please fill the fields with all the informations important for the maintainers to get your issue fixed or sorted out.

If you feel it's relevant, please attach screenshots or pictures that could detail the issue more.

* [ ] Issue with Checkpoint for 3DS
* [x] Issue with Checkpoint for Switch
* [ ] Feature request

### Error details

* Entrypoint: Hekate - CTCaer mod v2.3
* System version: 5.1.0
* Checkpoint version: 3.3.0
* Expected behaviour: when swapping between user you would expect it to automatically move to the top left corner in case there is not a title listed where the cursor is on another user 
* Encountered behavior: shown in screenshot 
* Steps to reproduce:
  * Select a save far into the list of games then switch to a user with less saves 
Sorry the images glitched out slightly 
![2018061415370601-db1426d1dfd034027cecde9c2dd914b8](https://user-images.githubusercontent.com/16693525/41434334-62a1ab3a-6fe9-11e8-9819-50522b54629e.jpg)
![2018061415370200-db1426d1dfd034027cecde9c2dd914b8](https://user-images.githubusercontent.com/16693525/41434336-6567070c-6fe9-11e8-9458-f5214cc53acd.jpg)

**Comment by BernardoGiordano** [comment]
Please check #101 and test the build I sent to fix this issue.
