### ISSUE TITLE
Error 0000F601 Failed to commit to save device when trying to restore save

### ISSUE THREAD

**Issue by NodeTechGaming** [BernardoGiordano/Checkpoint#112]
* [ ] Issue with Checkpoint for 3DS
* [x] Issue with Checkpoint for Switch
* [ ] Feature request

### Error details

* Entrypoint: hekate
* System version: 5.1.0
* Checkpoint version: 3.3.0
* Expected behaviour: Restoring save
* Encountered behavior: Not restoring save
* Result code (if available): 0000F601 (Also causes system crash with error 2011-0301)
* Steps to reproduce:
  * open checkpoint
  * restore a save of Minecraft (the new version)
  
I managed to backup/restore the save once perfectly fine, then this error started appearing afterwards. Not sure what happened. Any help is appreciated.
EDIT: I can still restore other saves, just not Minecraft.

**Comment by Pixelman546** [comment]
Same here, Sys version is 5.1.0 and Checkpoint is version 3.3.0. Also using the new bedrock edition of minecraft on the switch. Same error, and it only happens with minecraft.

**Comment by NodeTechGaming** [comment]
Managed to get it working again. You need to go into checkpoint, make a backup of the game, exit checkpoint, delete the games save data, open checkpoint, restore (probably modified) backup.

This should probably be added as an automatic procedure inside Checkpoint.
