### ISSUE TITLE
[Switch] Checkpoint crashes console when switching users unless the minus button has been pressed at least once

### ISSUE THREAD

**Issue by 98otiss03** [BernardoGiordano/Checkpoint#115]
* [ ] Issue with Checkpoint for 3DS
* [x] Issue with Checkpoint for Switch
* [ ] Feature request

### Error details

* Entrypoint: hekate
* System version: 5.1.0
* Checkpoint version: latest 3.3.0
* Expected behaviour: Switch between users
* Encountered behavior: System crash
* Result code (if available):
* Steps to reproduce:
  * step 1 - Launch Checkpoint
  * step 2 - Switch user before pressing minus

**Comment by BernardoGiordano** [comment]
This has already been fixed.
