### ISSUE TITLE
Write protected

### ISSUE THREAD

**Issue by CVFireDragon** [BernardoGiordano/Checkpoint#116]
my 3ds says the SD card is write protected after I put the cia in my CIAs folder. I cannot delete the cia help

**Comment by CTCaer** [comment]
You probably reached the max write possible on a specific block.

If that's the case, your sd card is now read-only, forever.
Try to communicate with your seller or manufacturer and see if you can replace it (RMA) free of charge.
(Normally they have 10y to lifetime warranties).
