### ISSUE TITLE
Keeps reading Pokemon Platinum as another game

### ISSUE THREAD

**Issue by LonginusSmasher** [BernardoGiordano/Checkpoint#119]
## Issue template

Please fill the fields with all the informations important for the maintainers to get your issue fixed or sorted out.

If you feel it's relevant, please attach screenshots or pictures that could detail the issue more.

* [x] Issue with Checkpoint for 3DS
* [ ] Issue with Checkpoint for Switch
* [ ] Feature request

### Error details

* Entrypoint: Roselina Homebrew Launcher
* System version: 11.7.0-40U
* Checkpoint version: 3.2.0
* Expected behaviour:
* Encountered behavior: It's saying I have a different game cartridge in my 3ds and that it doesn't have an ID#
* Result code (if available):
* Steps to reproduce:
  * step 1
  * step 2
  * ...
  
### Feature request details

* I would like this feature...:
* Because...:

**Comment by BernardoGiordano** [comment]
I'm sorry what's the issue here?

**Comment by LonginusSmasher** [comment]
I'd like to apologize too I wasn't very clear. I'm very new to homebrew and maybe I'm doing something wrong but here's the issue, I have a Pokemon Platinum cart in my new 2ds xl but when I boot up checkpoint it says I have FIFA WC and it has no ID #
![screenshot 1](https://user-images.githubusercontent.com/41141243/42722474-2835a396-86e8-11e8-9c19-c78a297c0f30.jpg)

**Comment by BernardoGiordano** [comment]
Fake cart, probably.

**Comment by LonginusSmasher** [comment]
Oh okay well shoot I take it your program doesn't work with roms

**Comment by BernardoGiordano** [comment]
It works with original carts only.

**Comment by LonginusSmasher** [comment]
Okay well thank you for the help
