### ISSUE TITLE
Problem with some games folder

### ISSUE THREAD

**Issue by RS55** [BernardoGiordano/Checkpoint#12]
Reviewing the program I'm stuck with for example Smash Bros (USA) or Professor Layton and the Azran Legacy (EUR), the directory is created but when you want to access it it is invalid, nor does it let it be eliminated. All this from Godmode9 but from the pc let me enter the Professor Layton but the Smash Bros no.

**Comment by BernardoGiordano** [comment]
This is currently being researched

**Comment by RS55** [comment]
Okay!

**Comment by fox8091** [comment]
I'm not exactly sure b5ddea7 closes the issue. I mean, it seems to remove spaces, but the actual issue is the folder containing a . in the name. That is breaking FAT standards, and breaks a lot of FAT drivers, including GodMode9's.
