### ISSUE TITLE
Error C8804478 When opening Checkpoint on N3DS 11.7

### ISSUE THREAD

**Issue by Sara06515** [BernardoGiordano/Checkpoint#120]
* [x] Issue with Checkpoint for 3DS
* [ ] Issue with Checkpoint for Switch
* [ ] Feature request

### Error details

* Entrypoint: CFW
* System version: 11.7
* Checkpoint version: 3.20
* Expected behaviour: load apps to backup on start
* Encountered behavior: loads 5 apps then gives an error, holding "B" to refresh results the same
* Result code (if available): Error C8804478

**Comment by Sara06515** [comment]
![20180715_105001](https://user-images.githubusercontent.com/41266133/42735149-26be8ef2-881d-11e8-830b-65fc970ee060.jpg)

**Comment by BernardoGiordano** [comment]
there's probably a system title it doesn't manage to load.

**Comment by Sara06515** [comment]
Is there a way for me to fix it?

**Comment by BernardoGiordano** [comment]
please tell me if this fixes the issue https://www.dropbox.com/s/cq5hcyrrdq3dj8s/Checkpoint.cia?dl=0

**Comment by Sara06515** [comment]
Nope, same. And this time when I press "B" to refresh I get the "An exception occurred" error

**Comment by Sara06515** [comment]
Any solutions available yet? Thank you for your time
