### ISSUE TITLE
Freezing After Deleting Saves And Attempting to Create Another Backup

### ISSUE THREAD

**Issue by TimetoDance** [BernardoGiordano/Checkpoint#121]
When I delete the save (any save) and try to back up again and hit "YES" to backing up - it freezes always requiring a hard reset. V3.3

**Comment by BernardoGiordano** [comment]
This should have been fixed already

**Comment by TimetoDance** [comment]
It's weird. When I create saves initially - it works...create multiple...A-OK. As long as I don't delete EVERY save and for it to go back to "new" in the same switch session - it won't freeze.

If I remove saves I made....and it goes back to "New" then it freezes...tested just now a lot.

**Comment by BernardoGiordano** [comment]
I mean, in the upcoming release. You can try that already if you have a chance to build it yourself

**Comment by TimetoDance** [comment]
Oh okay :D I thought maybe I did something wrong. Thank you for your quick reply! Godbless
