### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by fennectech** [BernardoGiordano/Checkpoint#123]
After deleting a save you are left with a screen that looks like this    if you try to create a backup without pushing up or down it will crash the entire console.  
![image](https://user-images.githubusercontent.com/11953665/43028652-ac5ebf28-8c46-11e8-84ea-80cb8942d5ad.png)

**Comment by BernardoGiordano** [comment]
fixed

**Comment by fennectech** [comment]
Issue still present on current build.
