### ISSUE TITLE
After deleting all saves in a game you cannot create a new save. 

### ISSUE THREAD

**Issue by fennectech** [BernardoGiordano/Checkpoint#124]
when deleting all backups you cannot create a new one  
![image](https://user-images.githubusercontent.com/11953665/43029027-07f7f3fc-8c49-11e8-894f-c0be6006febb.png)
When clicking the button to create a backup it just moves straight to this screen 
skipping the keyboard.

![image](https://user-images.githubusercontent.com/11953665/43029043-2320c4a6-8c49-11e8-9011-f263f782a9fd.png)
upon clicking yes it does this.  
![image](https://user-images.githubusercontent.com/11953665/43029004-f5871572-8c48-11e8-9be0-4e904abf0120.png)

**Comment by BernardoGiordano** [comment]
fixed

**Comment by fennectech** [comment]
Issue still present on a freashly compiled build.
