### ISSUE TITLE
crash when exiting target title after navigation

### ISSUE THREAD

**Issue by zweilous** [BernardoGiordano/Checkpoint#126]
* [x] Issue with Checkpoint for 3DS
* [ ] Issue with Checkpoint for Switch
* [x] Feature request

### Error details

* Entrypoint: rosalina
* System version: 11.6.0-39u
* Checkpoint version: 3.4.0 stable
* Expected behavior: pressing b should exit target title normally regardless of number/navigation of saves listed
* Encountered behavior: after exiting target title and attempting to navigate, application crashes or exits to homebrew menu
* Result code (if available):
* Steps to reproduce:
  * select a game title with multiple pages of saves listed (five saves or more)
  * navigate to the next page of saves with the up/down button or with zl/zr. the "new..." menu item shouldn't be visible
  * exit target title with b
  * press an arrow button to navigate and it crashes

also, as a side note, would it be possible for the left/right d-pad buttons to have the same behavior as zl/zr when navigating saves? it just feels more intuitive for pagination

**Comment by BernardoGiordano** [comment]
Fixed
