### ISSUE TITLE
Exclude physical 3DS game cards from caching

### ISSUE THREAD

**Issue by sceptios** [BernardoGiordano/Checkpoint#128]
* [ ] Issue with Checkpoint for 3DS
* [ ] Issue with Checkpoint for Switch
* [x] Feature request
  
### Feature request details

* I would like this feature: Exclude physical 3DS game cards from caching.
* Because: The loading speed provided by caching titles is nullified when opening Checkpoint when a different game is inserted than before. Since this is technically a newly installed title (at least from Checkpoint's perspective), the whole cache gets recreated every time this happens. I feel like it can be assumed that the inserted game card is subject to change and should be loaded every time.

**Comment by SpiredMoth** [comment]
Repeat of #61

**Comment by sceptios** [comment]
I had looked through the open issues to see if this had been submitted, and it seems I missed that one. Thanks for pointing it out. Since this is a duplicate, I'll close it.
