### ISSUE TITLE
[Feature Request] Japanese characters 

### ISSUE THREAD

**Issue by gajewsk2** [BernardoGiordano/Checkpoint#130]
## Issue template

* [] Issue with Checkpoint for 3DS
* [X ] Issue with Checkpoint for Switch
* [x] Feature request

### Feature request details

Japanese characters don't work. It makes it difficult to view japanese game saves. Thanks for the work on this!

**Comment by BernardoGiordano** [comment]
`Japanese characters don't work` where?

**Comment by fennectech** [comment]
Japanese characters cannot be written to a fat32 filesystem.     This is not a limitation of checkpoint but a limitation of (the ancient) fat32 itself from 1990

**Comment by BernardoGiordano** [comment]
This is not a thing I'm able to fix right now
