### ISSUE TITLE
Hard freeze & forced reboot on overwrite Backup->Yes and New Backup->OK on keyboard

### ISSUE THREAD

**Issue by Stone-D** [BernardoGiordano/Checkpoint#131]
## Issue template

* [x] Issue with Checkpoint for Switch

### Error details

* Entrypoint:
* System version: 4.1.0, SXOS 1.4, SDFiles521.zip
* Checkpoint version: 3.4.0
* Game being saved: Zelda BOTW 1.0 XCI patched via NSP to 1.5 plus DLCs
* Expected behaviour: proceed with the backup process
* Encountered behavior: hard freeze/crash, requiring a forced reboot
* Result code (if available):
* Steps to reproduce:
  * Click Zelda BOTW icon
  * click existing save
  * Click backup
  * Click Yes -> Freeze

* Possibly related information
  * The first attempt to create a new backup seems to result in a freeze upon pressing OK on the keyboard.
  * Seems to only work once, then attempting to save anything else will result in a hard freeze.

**Comment by BernardoGiordano** [comment]
Can't reproduce.
