### ISSUE TITLE
[CRASH] Zelda BOTW can backup save but hangs on restore

### ISSUE THREAD

**Issue by 877cms** [BernardoGiordano/Checkpoint#138]
## Issue template

Please fill the fields with all the informations important for the maintainers to get your issue fixed or sorted out.

If you feel it's relevant, please attach screenshots or pictures that could detail the issue more.

* [] Issue with Checkpoint for 3DS
* [X ] Issue with Checkpoint for Switch
* [ ] Feature request

### Error details

* Entrypoint: Ebay jog to RCM then sxos 1.5 payload via TegraGUI
* System version: 4.1.0
* Checkpoint version: 3.4.1
* Expected behaviour: restore save to Zelda BOTW - backed up moments before - NOT modified
* Encountered behavior: Backup works fine, when pressing R for restore it goes to next screen (press A to confirm), then hangs. Have to power down console. 
* Result code (if available): No code on screen
* Steps to reproduce:
  *Delete all software and saves on Switch and install fresh botw and 1.5 update via nsp (sdcard)
  *Load BOTW and play past opening scenes (to old man part)
  * Exit game and press X to exit software
  * Enter album>Homebrew tab>Checkpoint 3.4.1
  * Select user/botw and press LB to backup save game successfully
  * Select user/botw and press RB to restore save game - HANGS on screen to press A to continue
  * Console totally unresponsive - have to long press power button

### Feature request details

* I would like this feature...:
* Because...:

**Comment by BernardoGiordano** [comment]
Disable fs_mitm.

**Comment by 877cms** [comment]
Thanks for the quick reply! I'm using sxos and don't know how I can disable fs_mitm?
Sorry for being a dunce!
