### ISSUE TITLE
Professor Layton VS Phoenix Wright ExtData not detected

### ISSUE THREAD

**Issue by DjBlades** [BernardoGiordano/Checkpoint#139]
## Issue template

* [x] Issue with Checkpoint for 3DS
* [ ] Issue with Checkpoint for Switch
* [ ] Feature request

### Error details

* Entrypoint: CIA
* System version: 11.6.0
* Checkpoint version: 3.4.1
* Expected behaviour: Extra Data for Professor Layton VS Phoenix Wright - Ace Attorney to appear in the ExtData menu.
* Encountered behavior: Does not appear, shows in 3DS Data Management.
* Result code (if available):
* Steps to reproduce:
  * Import a 100% Completion save (I used this one https://puu.sh/BhP31/c6b50930c5.zip, American game)
  * Enter Extra Content, choose to download the bonus content.
  * Game will download to Extra Data, entry will not be visible in Checkpoint.

**Comment by BernardoGiordano** [comment]
Hold B to refresh titles.

**Comment by DjBlades** [comment]
Hmmm. It's now appeared (Just from turning my 3DS back on, though I rebooted it several times and it didn't appear then...) but the Extra Data doesn't seem to be restored correctly. I backed up the data, deleted it through Data Management, then restored it back on Checkpoint. There's no entry in Data Management and the game doesn't detect the content.

**Comment by BernardoGiordano** [comment]
Why are you deleting the data? You're not supposed to do that

**Comment by DjBlades** [comment]
To test that I could restore it properly. So with no existing extra data, it can't be restored?
I'm mainly doing this to transfer it over to Citra.

**Comment by BernardoGiordano** [comment]
Can't be restored if the archive isn't available and openable, it's a technical issue

**Comment by DjBlades** [comment]
Damn. The only way to create Extra Data in Layton VS Wright is to use the online download. I take it this means that it's impossible to import to Citra?

**Comment by BernardoGiordano** [comment]
Currently impossible, yes.

**Comment by DjBlades** [comment]
Guess I'll have to wait for an update. Thanks for the help anyways.

**Comment by lucasknook** [comment]
Do you still have the files? I have been searching for a long time and you seem to have them, the link does not work anymore.

**Comment by GriffinG1** [comment]
Please do not post on closed issues, especially not those that are two years old.
