### ISSUE TITLE
Speeding up backup/restoring process

### ISSUE THREAD

**Issue by Robz8** [BernardoGiordano/Checkpoint#15]
I previously used JKSM, and backup/restoring save files was fast, but with Checkpoint, it seems to be slightly slower.

**Comment by RS55** [comment]
I would like to add to this that it would be nice to add a progress bar and say by which title it goes like it happens in JKSM when backing up multiple games, I that I have little more than 10 games feel eternal without knowing how it goes, imagine someone with many more...

**Comment by BernardoGiordano** [comment]
@RS55 if you had checked the very last commit, you wouldn't have said this. https://github.com/BernardoGiordano/Checkpoint/commit/af10ec6cf72d77ffbabfca5397d120d7ab317a8d

@Robz8 I'm not sure there's a problem

**Comment by RS55** [comment]
Oh my bad, I had not seen it, sorry and thanks!

**Comment by Robz8** [comment]
I timed how long the backup processes for "Style Savvy: Fashion Forward", is in both apps.

Backup (creating new one): 
JKSM: 45 seconds
Checkpoint: 1 minute and 23 seconds

Backup (overwriting existing one):
JKSM: 17 seconds
Checkpoint: 1 minute and 23 seconds

Restore:
JKSM: 27 seconds
Checkpoint: 40 seconds

**Comment by BernardoGiordano** [comment]
I wasn't able to reproduce. Tried to backup all of my games at once and it took way less than the time it took you to backup Fashion Forward only.
