### ISSUE TITLE
Repeatable Crash when exporting Badge Arcade extdata

### ISSUE THREAD

**Issue by metaboss** [BernardoGiordano/Checkpoint#17]
Checkpoint 2.0.2 crashes consistently when exporting extdata for Badge Arcade (USA). It fails on the first file allbadge.sarc, which is a 70.74 MiB file. Could it be because of the filesize? JKSM exports the file successfully.  

I'm using the 3dsx build on 11.6, b9s 1.3 + luma 8.1.1

**Comment by BernardoGiordano** [comment]
What's the error code?
