### ISSUE TITLE
bottom screen red frozen

### ISSUE THREAD

**Issue by AL3XPI** [BernardoGiordano/Checkpoint#176]
* [x] Issue with Checkpoint for 3DS

### Error details

I just downloaded Checkpoint and put it on my N2dsxl and I loaded it up through the homebrew launcher and ended up with the bottom screen red and frozen. Please help.

* Entrypoint: Homebrew (Steelhax)
* System version: 11.8
* SD Card Filesystem: MicroSD
* Checkpoint version: 3.5.0
* Expected behaviour: Load into checkpoint
* Encountered behavior: Red screen frozen
* Result code (if available):

**Comment by Gudf** [comment]
You need CFW to use Checkpoint.
