### ISSUE TITLE
crashing when flashcart inserted

### ISSUE THREAD

**Issue by nkopas** [BernardoGiordano/Checkpoint#18]
I pretty much leave my R4i SDHC 3DS RTS flashcart inserted all the time. When using the CIA version of Checkpoint, after I exit the app the cartridge icon  on the home screen will disappear/reappear constantly until I eject it. Then the app will finally allow me to close it down. This doesn't happen when using the 3DSX version.

**Comment by nkopas** [comment]
just saw related discussion on r/3dshacks. let me know if you want me to do any testing or collect data for you.

**Comment by greenDarkness** [comment]
I just had a flash cart related issue as well. After backing up some saves, I pressed the home menu to exit, and my title selector kept moving to my cartridge slot which contained a flash cart.

**Comment by springsn0w** [comment]
I'm getting this issue as well, I have a DSTT and whenever I try to exit Checkpoint it freezes up on the "closing current software" grey screen. If I eject the flashcart when this screen is up it will close properly and everything seems to work fine after that.

**Comment by Soir09** [comment]
I have this issue as well on the .3dsx version with my R4i Gold RTS. In fact, it does it even when I don't backup/restore anything.

**Comment by Delphox** [comment]
Same issue here with Ak2i. When I open Checkpoint it keeps flashing the flashcard in and out.

**Comment by 16BitWonder** [comment]
Been having this same issue with the .cia build and my R4i Gold RTS. I click "X" to close it on the home menu and it just hangs when my flashcart is inserted.

**Comment by Valkyy** [comment]
Also been having this issue, program never closes (just hangs) and sometimes my flashcart will flicker in the home menu (meaning it looks like it's constantly being reinserted). I have to either remove the flashcart temporarily or shut down the 3ds which leads to a crash.
