### ISSUE TITLE
Extdata backup/restore occasionally fails.

### ISSUE THREAD

**Issue by BernardoGiordano** [BernardoGiordano/Checkpoint#2]

**Comment by siema** [comment]
Games I've found to crash:
- Pokemon Sun (error D900458B)
- Terraria (error D900458B)

Also, second attempt at backing up Terraria's extdata gave me an ARM11 exception. Photo of exception and dump attached.
What's weird, after restarting the app, it displays those backups as actually taken. Not sure about their completness though...

![20171001_154708](https://user-images.githubusercontent.com/537808/31055170-035bb5e6-a6c0-11e7-8eaf-29b7eb312f0d.jpg)
[crash_dump_00000005.zip](https://github.com/BernardoGiordano/Checkpoint/files/1347160/crash_dump_00000005.zip)

**Comment by BernardoGiordano** [comment]
They're not complete, so just ignore them.

**Comment by siema** [comment]
That's what I assumed :)
