### ISSUE TITLE
[Feature Request] Close Application on Button Press

### ISSUE THREAD

**Issue by greenDarkness** [BernardoGiordano/Checkpoint#20]
Hello,
I was wondering if you would consider adding the ability to shut down Checkpoint by pressing Start, or B twice? 
Thanks for all your work!

**Comment by BernardoGiordano** [comment]
START already kills the application...

**Comment by greenDarkness** [comment]
So, I just launched the CFW version of Checkpoint on Old3ds, and holding start did not shut down Checkpoint; instead it causes the application to freeze.

**Comment by BernardoGiordano** [comment]
You probably have a flashcard inserted, haven't you?
