### ISSUE TITLE
Crash after recognizing about 100 games.

### ISSUE THREAD

**Issue by cheatfreak47** [BernardoGiordano/Checkpoint#21]
Using the 3DSX build under Rosalina.
I have a lot of games on my 3DS and I've got a lot of save file, after about 100 titles are recognized, I get a crash. 
ErrDisp:
Processor: ARM11 (core 1)
Exception type: prefetch abort (kernel panic)
Current process: pxi (0000000000000000)

dump is attached here.
[Downloads.zip](https://github.com/BernardoGiordano/Checkpoint/files/1386263/Downloads.zip)

**Comment by BernardoGiordano** [comment]
do you have a flashcard inserted?

**Comment by cheatfreak47** [comment]
Ah, yes I did but I'm still crashing after about 100 games list without it inserted too. 
New dumps: 
[Downloads.zip](https://github.com/BernardoGiordano/Checkpoint/files/1389175/Downloads.zip)

Now it says ARM11 (core 0), Execption: data abort instead.
Same crash though. I think maybe Luma was displaying another error because of the flashcart.

**Comment by cheatfreak47** [comment]
Oh right, and the app was 3dsx_app instead of pxi like before

**Comment by dalekman9999** [comment]
Gotten the exact same error too @cheatfreak47

**Comment by cheatfreak47** [comment]
Still waiting on a fix for this one, it's pretty much the only thing preventing me from using Checkpoint over JKSM most of the time. 👍

**Comment by cheatfreak47** [comment]
This is still very much a problem, and kind of a mean problem too.
Out of the blue I decided to build the latest version (cccb9749) and I can confirm that indeed, this is still an issue, even on the very latest of builds. I am, of course, using Luma3DS v9.0 and I am running this with the Rosalina based Homebrew Launcher.

Here is a picture of the error displayed by Luma 3DS's exception handler:
![photo_2017-12-23_12-07-07](https://user-images.githubusercontent.com/7818664/34321340-6eedea8a-e7da-11e7-8356-f2863cb3f07c.jpg)

And here is the crash dump produced by the error handler:
[crash_dump_00000015.zip](https://github.com/BernardoGiordano/Checkpoint/files/1584308/crash_dump_00000015.zip)

Now, I don't know _that_ much about actual programming but I have common sense when it comes to this sort of thing, so if there's something I can do to help debug and fix this problem, let me know.

**Comment by BernardoGiordano** [comment]
I'm not able to test by myself since I don't have that much game, so I'll require you to test out some builds that may fix the problem. Join this discord server to keep in touch https://discord.gg/bGKEyfY
