### ISSUE TITLE
Unable to restore ExtData after editing 

### ISSUE THREAD

**Issue by Lushlox** [BernardoGiordano/Checkpoint#23]
The game in question is monster hunter Generations, I'm not sure if this is a title specific issue or not though as this is the only title I have tried it with. The issue is as the title states, I click "restore" and it "finishes" instantly, accomplishing nothing. Exporting the data is working as intended, but restoring it after being edited doesn't seem to work. This occurred  for me in both a previous version as well as this current release build. 

Thank you for your work though, it's an amazing tool.

**Comment by ShobuPrime** [comment]
I have the same issue with Monster Hunter Stories.

To verify I wasn’t going crazy, I performed a restore of EXTdata with Jk save managemer and was able to successfully restore an edited save file that way.

**Comment by AlternativeZero** [comment]
Just wanted to add that this issue also applies to Monster Hunter XX, with JKSM I was able to restore the extdata successfully but with Checkpoint it looked liked it worked but it didn't restore the save data and this was after updating to v2.0.2.

Hopefully this can be fixed soon because it's a very important issue.

**Comment by pixelmasher** [comment]
It doesn't work for Fantasy Life as well. It's just broken.

**Comment by liugongkai111** [comment]
Same here for Monster Hunter XX. The Exdata backup seems broken.

**Comment by pixelmasher** [comment]
It seems to backup fine, but restoring doesn't work. You can use JKSM to restore Checkpoint backup.

**Comment by BernardoGiordano** [comment]
This should fix the issue. Anyways, I want you to test it out and report back if the game loads correctly after restoring. I don't take responsibility if that accidentally happens. The problem is under investigation

https://www.dropbox.com/s/jt2uuv1slqsefta/EXTDATAFIX.cia?dl=0

**Comment by BernardoGiordano** [comment]
**Test this one and let me know**: https://www.dropbox.com/s/vjetot456e85nzt/EXTDATAFIX.cia?dl=0

**Comment by Robz8** [comment]
Can confirm this works!

**Comment by BernardoGiordano** [comment]
this may still contains some bugs though, so wait for the new stable release if some of you are unsure
