### ISSUE TITLE
Not loading all games/apps

### ISSUE THREAD

**Issue by scionae** [BernardoGiordano/Checkpoint#24]
Well, I have around 60/70 games installed and it only loads 32 of them?
Why is that happening? 
This occurs with both the .cia and .3dsx

**Comment by BernardoGiordano** [comment]
From the readme:

> Checkpoint supports DS cartridges, normal titles, and demos. It also automatically checks and filters homebrew titles which may not have a save archive to backup or restore, which is done without an external title list and filters. For this reason, Checkpoint doesn't need constant user maintenance to retain full functionality.

**Comment by scionae** [comment]
Well, I have to restore a save for a game that I've re-installed but I can't do it since it's not showing up :/
I can start a new file and then restore it back, but it's a pain to do everytime with every game

**Comment by BernardoGiordano** [comment]
open the game until it creates the save data and then it will appear in Checkpoint

**Comment by tkolarik** [comment]
I am having the same issue, multiple titles which already have save data are not showing up from the virtual console and from installed cias

**Comment by GriffinG1** [comment]
@tkolarik please do not post on 2 year old closed issues. Read the README.

**Comment by LeonardoLimaMH** [comment]
This problem continue.

Does not show all the games, even with already some saves.

Two games is not working in mine 3ds, Monster Hunter XX and Fantasy Life

**Comment by ruppke** [comment]
Same problem I'm trying to get cheats for mc 3ds but i can't

**Comment by GriffinG1** [comment]
This issue has been closed for over 4 years. Refer to this photo. I am locking this issue.
![image](https://user-images.githubusercontent.com/28538707/156941013-5ac26adb-b99c-4fa5-acae-57023745c9be.png)
