### ISSUE TITLE
[Feature Request] Backup/Restore Confirmation

### ISSUE THREAD

**Issue by crazygai** [BernardoGiordano/Checkpoint#25]
Is it possible for Checkpoint to ask for a confirmation when overwriting an existing backup or when restoring a backup? This would help minimize the chance of accidentally deleting an important save file.

**Comment by suloku** [comment]
Yes, I think this is a much needed feature, at least for me and possibly many other people.
I understand some people wouldn't want the confirmation, so maybe some way to configure it, even by manually editing a config file? Maybe just an empty file that wen present at a certain SD path toogles the confirmation menu on?
