### ISSUE TITLE
Not all games showing up

### ISSUE THREAD

**Issue by NinFanBoyFTW** [BernardoGiordano/Checkpoint#29]
Hi. Every time I open the program, it refreshes the games and takes forever to load instead of being cached. Im pretty sure its being caused because all of my games are not being loaded. I have tons of games on my 3ds (100+) and it is only seeming to load around 50 of them. I took my flash cart out and it is still doing the same thing. Thanks

**Comment by BernardoGiordano** [comment]
From the readme:

> Checkpoint supports DS cartridges, normal titles, and demos. **It also automatically checks and filters homebrew titles** ***which may not have a save archive to backup or restore***.

This also applies to titles which hasn't been played at least once. The titles you see are the titles that can effectively work with any save editor.

Can you please document yourself better before reporting non-existent issues?

**Comment by NinFanBoyFTW** [comment]
Ok but still whenever I open up the program it takes a few minutes to load all of the games even though I have done it multiple times now. Isn't it supposed to come up with all of the games that were already cached and then press the refresh button if you need to check for more games like it works in jksm.

**Comment by CooLowbro** [comment]
This still happening. I tested with two different consoles, one the game shows up, and the other one doesnt. The one that shows is a normal 3DS, the other one is a 3DSXL. Both with pokemon moon.
