### ISSUE TITLE
Use unused buttons (are L/R unused?) to backup/restore the save

### ISSUE THREAD

**Issue by egzonqj** [BernardoGiordano/Checkpoint#3]
Pretty much the title, I use JKSM and to navigate you use the buttons, it would be awesome if you can trigger the Backup/Restore touch-buttons with some phyisical unused ones (like L/R if they are not being used by the app) 

But I guess the first entry (naming the save folder) would be without this option

This is just an enhancement suggestion, thanks again Bernardo for your hard work!

**Comment by BernardoGiordano** [comment]
L and R are used to switch between pages if you have more titles installed, so I think this is not feasible as for now.

**Comment by egzonqj** [comment]
Couldn't them be re-used when selecting the game you want to backup/restore? (I don't know how does the app manages the physical button use)
