### ISSUE TITLE
change the name of the game folder in sd card

### ISSUE THREAD

**Issue by NinFanBoyFTW** [BernardoGiordano/Checkpoint#30]
Hi. This is kind of a continuation of one of my other suggestions but I wanted to know if there is a way for you to make the folders for the games on the sd card have their ID after the name of the game. Every time I am looking for a game after I export it, I have to look through all of the games to figure out where my game is listing instead of just knowing that pokemon sun comes after pokemon moon alphabetically. I know it may be nitpicking but it makes the whole experience much more time consuming compared to JKSM, and I really want to be able to use this since it seems much more efficient in the ways jksm isn't. Thanks

**Comment by BernardoGiordano** [comment]
I don't think this would be possible anymore, lots of people are already using it from months and changing the working path at this point would be really bad for people. You can always build your own custom copy with the working path you wish, it's just a single line change
