### ISSUE TITLE
[Feature Request] Please add serial to information displayed

### ISSUE THREAD

**Issue by pixelmasher** [BernardoGiordano/Checkpoint#32]
Please add the serial to the information displayed. If you have multiple games with the same icon, there's no way to tell which on is which without remembering the Title ID. JKSM displays the serial so it's very easy to tell which one is which.

**Comment by BernardoGiordano** [comment]
I'm not sure what's the problem here. Mediatype and title are enough to distinguish two titles with the same icon

**Comment by pixelmasher** [comment]
That doesn't help when you have multiple region copies of the game.

**Comment by BernardoGiordano** [comment]
Serial code doesn't mean anything. Could you be more specific?
