### ISSUE TITLE
[Feature Request] Graphic toggle option

### ISSUE THREAD

**Issue by pixelmasher** [BernardoGiordano/Checkpoint#35]
Could we get an option to toggle between a list view like JKSM, list view with little icon like DS flashcart, and current icon view? I'm good with any option for a speedy list view. Icons certainly looks nice, but it's very slow. Every time I start the app, I spend way longer waiting for the icons to load than to actually backup/restore game saves.

**Comment by BernardoGiordano** [comment]
The icons don't take the amount of time to load you're expecting. The whole process of fetching the backup folders and testing the save partitions take time, because they're IO operations.
