### ISSUE TITLE
[Feature Request] Delete backups

### ISSUE THREAD

**Issue by Lavorther** [BernardoGiordano/Checkpoint#36]
Loving the program so far, much easier and intuitive than SaveDataFiler. I'm really missing the option to delete your backups though. I'm obsessive like that, I like to remove all backups I no longer need immediately. Right now I have to pop my SD card into my computer to do that, it would be nice to have that function build into the program itself.

**Comment by GriffinG1** [comment]
As a note, until it's added you can use godmode9 or fbi to delete them
