### ISSUE TITLE
[request] VC sav conversion

### ISSUE THREAD

**Issue by Ninjistix** [BernardoGiordano/Checkpoint#42]
What I am referring too is the VC sav file size difference and EMU

the VC gives you 32,784, the EMU gives you 32,812

[Silver EMU.zip](https://github.com/BernardoGiordano/Checkpoint/files/1577796/Silver.EMU.zip)
[Silver VC.zip](https://github.com/BernardoGiordano/Checkpoint/files/1577797/Silver.VC.zip)

the current solution for me, is having to add or remove a extra lines of code using HxD in order to restore the file to the VC after playing it on a emulator, luckily PKHeX does not modify the file size of the VC copy, so there's nothing to fix after editing it

**Comment by BernardoGiordano** [comment]
That's a problem with the emulator, not with checkpoint itself.
