### ISSUE TITLE
Not an issue! AK2i part of save incompatibility.

### ISSUE THREAD

**Issue by Fallenleader** [BernardoGiordano/Checkpoint#45]
Just here to report that regarding:
>
Notice: You mustn't have a flashcard inserted when launching Checkpoint, due to possible incompatibilities that could cause some threads to not end, possibly causing crashes.
> 
Acekard 2i is one of these flashcarts that will cause freezing and even requires a cold reboot of the 3DS.
I am using a legitimate AK2i and an O3DS on B9S with Luma 9.0 on firm 11.6.0-39U.

I just wanted to clarify to users here that this is one of possibly many incompatible flashcards, and removal of such will prevent a crash.

**Comment by BernardoGiordano** [comment]
nice report but that has been already fixed days ago.

**Comment by Fallenleader** [comment]
Great to know :D 
Hope to assist in the future if possible.
