### ISSUE TITLE
Crashes system on Luma3ds 9.0 when exiting from HBL

### ISSUE THREAD

**Issue by BlazeUchiha420** [BernardoGiordano/Checkpoint#48]
Titles says it all. Almost every time I exit the app(3dsx version) from HBL it hangs on the closing software screen until I manually turn off the console. Pretty sure that didn't happen before the Luma update.

**Comment by Jmelz** [comment]
Same here.

**Comment by BernardoGiordano** [comment]
Pretty sure this is not an issue anymore in the latest codebase, I'm using HBL to test all the time. I think you have a flashcard inserted.
