### ISSUE TITLE
Exit button

### ISSUE THREAD

**Issue by Ninjistix** [BernardoGiordano/Checkpoint#49]
At the bottom of the screen it says press home to exit, but that just suspends the app, pressing start actually exits you from the app

also, would it be possible to add the option to rename a backup?

**Comment by james-d-elliott** [comment]
This is with new-hbmenu. Ideally exiting would take you back to new-hbmenu when you're using this method. I'd suggest setting start as the exit key. I might figure out how this is done in other repos and see if I can implement it.

**Comment by BernardoGiordano** [comment]
Start already is the exit button

**Comment by Ninjistix** [comment]
yeah i'm aware start is the exit button, im referring to the bottom of the screen it says [press the home button to exit] gui is  wrong

**Comment by Ninjistix** [comment]
![68747470733a2f2f692e696d6775722e636f6d2f4e74746b3868582e706e67](https://user-images.githubusercontent.com/12572974/34902605-0f8db160-f7ed-11e7-8c66-f9493523e53e.png)
this is what I'm referring too, should it be "start to exit"

**Comment by Robz8** [comment]
I think it should say, "Press 'HOME icon' to return to HOME Menu, or press START to exit.".

**Comment by BernardoGiordano** [comment]
Fixed in local branch, code will be updated eventually in the future
