### ISSUE TITLE
Is Graveyard Keeper not supported by this?

### ISSUE THREAD

**Issue by continue47** [BernardoGiordano/Checkpoint#492]
I installed checkpoint from the HB App store on my switch, most of my other games were showing up, but not Graveyard Keeper. Is the game not supported or am I doing something wrong?

I'm trying to export my save from the switch and get it on my PC.

Thanks.

**Comment by impeeza** [comment]
May be CheckPoint needs update, can you test JKSV from https://github.com/J-D-K/JKSV/ and let us to know if with this Homebrew you can access the savegame?

Also try to load Homebrew Loader using a title different to Graveyard Keeper and try again.

**Comment by continue47** [comment]
Thanks for the reply!

I managed to figure it out: it wasn't showing up because it was among the few games that only my girlfriend plays. After launching Checkpoint I had to tap on my profile picture somewhere on the bottom right and select her profile, and it showed up since only that profile had a save file on it. 

_In case anyone in the future wants to move a Graveyard Keeper save file from Switch to PC, this is how I did it:_
I got the .dat file (in my case 1.dat) from the Checkpoint export, it was under the folders Progress/DataPath. This needs to be put in "%UserProfile%\Appdata\LocalLow\Lazy Bear Games\Graveyard Keeper\". You need to have atleast one save already made on PC to replace the 1.dat with the new one. There is also a 1.txt file created on PC that I couldn't find on the switch export, which contains the game time and the number of skulls and crosses - I edited that with a text editor to match the save from the switch.
