### ISSUE TITLE
[Feature Request] XCI version of Checkpoint with its own four unique bin files for MIG Switch flash cards

### ISSUE THREAD

**Issue by R2MGaming** [BernardoGiordano/Checkpoint#493]
I used Checkpoint mostly on my V1 Switch to backup my saves from my Pokémon games (which I did use with PKHex one time), and it has helped me with Pokémon related stuff, but here is what I am thinking for a request: "Do you know that the MIG Switch flash card is available to buy online from the MIG Switch store? I've heard it can be used to play backups of certain Switch games with the XCI files and their four unique bin files (the initial data, the certificate, the card ID, and the card UID bin files) so what I am thinking of is seeing an XCI version of Checkpoint with its own unique four bin files (without using Custom Firmware) on the Switch with a feature that prevents it from being detected by Nintendo's servers and prevent it from being on the user's activity log (mostly to prevent bans on unmodded Switch consoles) and work like it usually does on CFW Switch consoles for save backups without NSO's Cloud Saving."

I know this may be difficult, and won't happen, but if it's possible I'd love to see it happen without ban risks.

**Comment by BernardoGiordano** [comment]
I'm sorry, this is not happening.

**Comment by impeeza** [comment]
@R2MGaming What you are asking IS NOT how the MIG works, if you are a MIG user and do not want be banned or worst ban someone else PLEASE read the MIG documentation, go to GBATemp and search for the MIG threads like https://gbatemp.net/threads/the-mig-switch-thread.651852/

It is imperative to you to learn the basics of the device and even more the basics of the Nintendo Switch Console.

@BernardoGiordano Thanks a lot for all your hard work.

**Comment by R2MGaming** [comment]
> I'm sorry, this is not happening.

Very well then.

**Comment by R2MGaming** [comment]
> @R2MGaming What you are asking IS NOT how the MIG works, if you are a MIG user and do not want be banned or worst ban someone else PLEASE read the MIG documentation, go to GBATemp and search for the MIG threads like https://gbatemp.net/threads/the-mig-switch-thread.651852/
> 
> It is imperative to you to learn the basics of the device and even more the basics of the Nintendo Switch Console.
> 
> @BernardoGiordano Thanks a lot for all your hard work.

I don't have a MIG Switch flash card unfortunately.
