### ISSUE TITLE
DS and 3DS codes from codejunkies, all there in xml files

### ISSUE THREAD

**Issue by HathewayWill** [BernardoGiordano/Checkpoint#498]
[Default Codelist US.zip](https://github.com/user-attachments/files/17580522/Default.Codelist.US.zip)

**Comment by BernardoGiordano** [comment]
Thanks for your contribution, although this should be a pull request. Feel free to submit a valid one

**Comment by HathewayWill** [comment]
Sorry re reopening this but I don't know how to do that.  Which is why I just uploaded the zip files with the xml files for you to utilize
