### ISSUE TITLE
Ability to refresh or recognize a cartridge insert/eject

### ISSUE THREAD

**Issue by JBoughter** [BernardoGiordano/Checkpoint#5]
More of a feature for convenience, but could you make it possible to either detect when the cartridge is ejected and inserted, or at least make a button (perhaps Y?) that refreshes and checks for a cartridge? It'd be quite convenient instead of restarting so it can see it. Along with this, trying to do multiple dumps of cartridges can get a bit tedious without this.

**Comment by BernardoGiordano** [comment]
fixed by https://github.com/BernardoGiordano/Checkpoint/pull/19
