### ISSUE TITLE
handling multiple save's in same folder

### ISSUE THREAD

**Issue by Ninjistix** [BernardoGiordano/Checkpoint#50]
I was messing around with my pokemon x save, and renamed the main to `bak`, I had the newly edited `main` in the same folder (because I assumed checkpoint would read the `main` first), but upon doing a restore, it restored the data from the `bak` file and not the `main`.

I'm just going to assume its not proper practice to have multiple sav files in the same folder, but I figure this could lead to similar problems down the road.

**Comment by proflayton123** [comment]
+1 with this
