### ISSUE TITLE
Ability to Change Paths of Files

### ISSUE THREAD

**Issue by ricksee** [BernardoGiordano/Checkpoint#51]
I don't know if this can be done, but the ability for the options to change paths for the root, save, and extdata to whatever we want. For instance, if I wanted to move it to another folder/directory, or move the save data to the root of the SD card instead of going to 3Ds/Checkpoint/...

Overall, this recent update has fixed alot of stuff and it is amazing. I hope you have a safe and glorious new year!

**Comment by BernardoGiordano** [comment]
I don't have plans to implement this.
