### ISSUE TITLE
not showing more than 20 titles

### ISSUE THREAD

**Issue by MarioMasta64** [BernardoGiordano/Checkpoint#52]
checkpoimt wont show me anymore titles after it shows 20

**Comment by BernardoGiordano** [comment]
> It also automatically checks and filters homebrew titles which may not have a save archive to backup or restore

**Comment by MarioMasta64** [comment]
then maybe turn that filter off? (restore mode) sometimes you need to restore data to a redownloaded title.  having it optional or toggable would be nice.

**Comment by BernardoGiordano** [comment]
Not in my plans. If you want that title to appear in the list, just open it up once and let the game create a save archive. It's technically impossible to do anything if a save archive doesn't exist.

**Comment by MarioMasta64** [comment]
oh, okay. feel free to close then.
