### ISSUE TITLE
"Fantasy Life" game not appearing

### ISSUE THREAD

**Issue by karikatourea** [BernardoGiordano/Checkpoint#54]
I can't back up my save for this certain title. It's not appearing on my list of games. I purchased the dlc expansion so probably that's the reason, though I haven't checked if I could back up my save before that.
If there's any chance to fix that it would be really nice, I invested a good amount of hours already and I don't trust my sd card that much.
Thanls in advance!

**Comment by ihaveamac** [comment]
this game doesn't save to savedata, everything goes in extdata.

**Comment by karikatourea** [comment]
Noob question (sorry). How does that work and what's the difference? Does that mean there's no way to back up?

**Comment by Robz8** [comment]
Press X to switch to backing up extdata.
