### ISSUE TITLE
Not load all apps and games

### ISSUE THREAD

**Issue by Saul0121** [BernardoGiordano/Checkpoint#58]
I have maybe 60 games and the app only detects 20

**Comment by BernardoGiordano** [comment]
> Checkpoint supports DS cartridges, normal titles, and demos. **It also automatically checks and filters homebrew titles which may not have a save archive to backup or restore**, which is done without an external title list and filters. For this reason, Checkpoint doesn't need constant user maintenance to retain full functionality.
