### ISSUE TITLE
[Idea] Delete Saves

### ISSUE THREAD

**Issue by Saul0121** [BernardoGiordano/Checkpoint#59]
My idea is a button to delete save data on the app

**Comment by BernardoGiordano** [comment]
you can already delete save backups

**Comment by SpiredMoth** [comment]
Maybe I'm wrong, but I think @Saul0121 might be referring to the game's current save

**Comment by Saul0121** [comment]
My idea is delete game save, not save backup.

**Comment by BernardoGiordano** [comment]
Any reason why it should be a relevant addition ot have?

**Comment by Saul0121** [comment]
For me it is very important to eliminate saves from a game, i need it too much.

**Comment by SpiredMoth** [comment]
Some people like to replay games and not all provide a way to delete their save
