### ISSUE TITLE
[Feature Request] Go down/up skipping some saves with right/left arrow key

### ISSUE THREAD

**Issue by Real96** [BernardoGiordano/Checkpoint#60]
Can you add this feature? :) Pressing Left/Right arrow key to go down to the next save file that isn't showed in the screen. Hope i explained it in a good way xD

**Comment by BernardoGiordano** [comment]
better you explain this in italian!

**Comment by Real96** [comment]
Come ha scritto il ragazzo, pagina successiva/precedente usando i tasti Destra/Sinistra. Perchè jo notato che lo scorrimento è abbastanza lento quando si hanno molti salvataggi, poichè bisogna premere giù/su tante volte per scendere/salire (l'applicazione è fantastica ovviamente!),

**Comment by BernardoGiordano** [comment]
You can press L/R to change page as well, no need to use DPAD left and right arrows

**Comment by Real96** [comment]
OH! Didn't know this, thanks a lot! you can close the issue :)
