### ISSUE TITLE
Do not filter cartridge if there is a backed up save for digital

### ISSUE THREAD

**Issue by bdougherty** [BernardoGiordano/Checkpoint#62]
I wanted to copy/move a save from a digital version to the cartridge version, but the cartridge didn't show up until I created a save in it first. I was thinking about it and I think it would be helpful at least to not filter out the cartridge if there is a backed up save from the digital version. (I think that would also be a good idea for all games, though.)

If something like that is not possible, always showing the cartridge would be helpful.

**Comment by BernardoGiordano** [comment]
It's not possible to not filter, due to the save archive unaccessible in every case. You're always required to create a save first.

**Comment by bdougherty** [comment]
Is there any way to make it clear in the interface that a save has to exist first? Right now there is no indication at all and at first I thought it was broken.
