### ISSUE TITLE
Radiant Historia - Perfect Chronology Save File - why is extdata folder empty and what to do to restore saves?

### ISSUE THREAD

**Issue by tocy777** [BernardoGiordano/Checkpoint#65]
So I just wanted to remove an old leftover from another game in the Extra Data menu I accidentally clicked on Radiant Historia's and pressed delete... I tried restoring it via Checkpoint to no avail (I did two backups), it wont show up ingame, I took a look at my SD Card and there is nothing in the extdata folder in the checkpoint folder but in the savefiles folder there is the rh3dsyst.sav file. What should I do? :'(

**Comment by BernardoGiordano** [comment]
If you deleted it I'm sorry, but I can do nothing to help. Try using tools like recuva to restore deleted files.
