### ISSUE TITLE
Crash when having the same game twice

### ISSUE THREAD

**Issue by Blacklands** [BernardoGiordano/Checkpoint#66]
I just had the case where I had the same game (Monster Hunter 3 Ultimate) twice inside of Checkpoint.
This was because I had the cartridge of the game inside my DS, as well as an installation of the game on the SD card (I dumped my cartridge into a CIA file using [GodMode9](https://github.com/d0k3/GodMode9), then installed the file with [FBI](https://github.com/Steveice10/FBI)).

Initially, starting up Checkpoint works fine. It recognizes two games, both with the same name and ID, and one as being on a cartridge, the other one as being on the SD card.
When I create a savegame (or extdata, doesn't matter) backup for either of the two versions, however, things start to break:

- Creating a backup for either version also makes it show up for the other version.
- Attempting to start Checkpoint again after a backup has been created will make it crash immediately (can provide the crash dump and/or a screenshot of the exception, if wanted). You can briefly see the UI, then it chokes and dies.

I suspect this happens because the folder names for the created backups (`[{ID} {Name}]`) do not include the differentiation between "game on cartridge" and "installed game on SD card" - normally this isn't a problem, however in this rather rare case where you have the same game for both and at the same time, it breaks.

I don't know what breaks exactly. Maybe it tries to open the files twice, or it's something with the cache files Checkpoint creates.
But it might be easy to fix by just adding some identifier somewhere into the names of the created folders, a number or a string, that differentiates between "game on cartridge" and "installed game on SD card" - so two versions of the same game can coexist correctly.

Oh, and I can confirm that if you remove the game cartridge after having taken a backup and then start Checkpoint, it does _not_ crash - so I'm pretty sure that this is indeed the problem.

If you need additional information or screenshots, I can provide them.

**Comment by ForcedToRock** [comment]
Same issue here. Deleting the cache files works created by Checkpoint works.

**Comment by BernardoGiordano** [comment]
Unable to reproduce.
