### ISSUE TITLE
[unimportant bug] Specific game not showing up

### ISSUE THREAD

**Issue by dimateos** [BernardoGiordano/Checkpoint#68]
I was trying to backup **Pokemon Moon** but it did not show up in checkpoint (there was savedata _for sure_). I tested it several times though. Then I tried your **PKSM** and there it was. Weirdly enough after exiting PSKM without saving then checkpoint also recognized the save.

Only happened with this game and idk if I could reproduce it. Just reporting this in case of something weird related happens so you can be aware.

Both checkpoint and pksm, great pieces of software, ty!

**Comment by MalikTH** [comment]
Cartridge or digital/CIA? I use the CIA and it shows up fine for me.

**Comment by BernardoGiordano** [comment]
Unable to reproduce, closing
