### ISSUE TITLE
Not all Slots are saved of Radiant Historia: Perfect Chronology (EUR)

### ISSUE THREAD

**Issue by xadox-1st** [BernardoGiordano/Checkpoint#69]
While backing up the save in _Radiant Historia: Perfect Chronology (EUR)_ only the first 6 slots of all 14 are saved.

**Edit:**
JKSM does backup only the first 6 slot, also.

**Comment by SuperOkazaki** [comment]
I know I'm late to the party, but maybe the other slots are in extdata?

**Comment by xadox-1st** [comment]
Thx for that tip. You where totaly right.
The other save slot are under the ExData.

**Comment by BernardoGiordano** [comment]
Closing as it is fixed now
