### ISSUE TITLE
[Feature] Built in FTP

### ISSUE THREAD

**Issue by xXAquaNightXx** [BernardoGiordano/Checkpoint#7]
Is it possible for the app to have a built in ftp. So saves can be easily transferred to PC and back without having to use multiple apps.

**Comment by BernardoGiordano** [comment]
Maybe just TCP. I'll close this now, and implement some TCP functions when it's time.

**Comment by Ninjistix** [comment]
was just about to request something like this (but i search current/closed issues first), like op said something like this would be easier to export > modify > import savs back without multiple HB apps.

**Comment by Ninjistix** [comment]
i think this should be reopened to not be forgotten, maybe a planned feature tag too? idk just saying, (its been awhile)

**Comment by BernardoGiordano** [comment]
It's already in the works and partially committed, no need for this to be reopened

**Comment by Ninjistix** [comment]
oh okay, must have missed the commits, thanks 👍
