### ISSUE TITLE
[switch] ERROR:0000F601 Failed to commit to save device.

### ISSUE THREAD

**Issue by xaliax** [BernardoGiordano/Checkpoint#70]
## Issue template

Please fill the fields with all the informations important for the maintainers to get your issue fixed or sorted out.

* [ ] Issue with Checkpoint for 3DS
* [ x ] Issue with Checkpoint for Switch
* [ ] Feature request

### Error details

* Entrypoint: HBL
* System version: 3.0.0
* Expected behaviour: RESTORE SAVES
* Encountered behavior: ERROR
* Result code (if available): ERROR:0000F601 Failed to commit to save device.
* Steps to reproduce:
  * step 1- backup BoTW saves
  * step 2 - restore BoTW saves

**Comment by reminon** [comment]
Delete the saves folder and start again. That fixed it for me.

**Comment by xaliax** [comment]
Did not fix it for me

**Comment by yellows8** [comment]
Does the system always freeze?

**Comment by reminon** [comment]
Try restoring just the save you need. Make a copy of the saves folder and put it somewhere safe. Then in the folder you want to restore delete all saves but the one you are wanting to restore. I had an issue with afterbirth, where it backed up 12 saves "most were quick saves", and wouldn't let me restore unless I only restored the one I needed.

**Comment by xaliax** [comment]
I advice not to do what reminon just mentioned as that deleted all of my saves and the switch thought that zelda was booting 

I had to put everything on save 0 (game_save.dat, caption.sav & caption.jpg and also the entire tracker folder and option.sav on root.

This worked and now I have a single modded save file and everything is working fine

**Comment by Shinigati** [comment]
@xaliax This didn't work for me but ehh that's just the sacrifice to getting unofficial support for >4.x.x hbmenu, compatibility issues are bound to happen until atmosphere officially drops.

**Comment by xaliax** [comment]
@shinigati i don’t know what you are taling about, I’m using 3.0.0 with the official HBL. Thi release was made for that.

**Comment by BernardoGiordano** [comment]
fixed in 911375a63beabbec46af4f7f03a5bcdbafa75526
