### ISSUE TITLE
the switch link is down 

### ISSUE THREAD

**Issue by manofsteel2017** [BernardoGiordano/Checkpoint#78]
tried to look for the 3.1.0 all over the link
all links are down.
can you fix that 

thanks

**Comment by mailwl** [comment]
it required new libnx (compiled from latest source). here I compiled 2 days ago:
[Checkpoint.zip](https://github.com/BernardoGiordano/Checkpoint/files/1998701/Checkpoint.zip)

**Comment by Leonidas2015** [comment]
@mailwl so are you saying the file you provided has the latest libnx?

**Comment by mailwl** [comment]
so far, yes. latest libnx, latest Checkpoint. but better if you will compile it by yourself to get all new updates
