### ISSUE TITLE
Error 2011-0301 when I backup my game Nintendo Switch 

### ISSUE THREAD

**Issue by Simats13** [BernardoGiordano/Checkpoint#79]
* [x] Issue with Checkpoint for Switch

### Error details
* Entrypoint: Hekate 5.x
* System version: 5.0.2
* Checkpoint version: 3.1.0
* Expected behaviour: launch nro
* Encountered behavior: Impossible to backup my game
* Result code (if available): 2011-0301
* Steps to reproduce:
step 1: launch Hekate on RCM Mode
step 2: launch HBM
step 3: launch Checkpoint
![img_2675](https://user-images.githubusercontent.com/39007520/40047716-7efa78b4-5830-11e8-933c-66dcc5dfa281.JPG)

I have this error message when I want to backup my game.

**Comment by Simats13** [comment]
Nobody know ?

**Comment by piklz** [comment]
Maybe it's a particular game? I tried it on 5.0.2 switch and it's written files correctly as far as i can tell

**Comment by BernardoGiordano** [comment]
Also, what's your username?

**Comment by Simats13** [comment]
I solved my problem, because the file was badly created from my computer and it could not work. Everything works now you can close it ;)
