### ISSUE TITLE
Save dump not appearing when Switch profile username contains special characters

### ISSUE THREAD

**Issue by Krarche** [BernardoGiordano/Checkpoint#81]
* [ ] Issue with Checkpoint for 3DS
* [x] Issue with Checkpoint for Switch
* [ ] Feature request

### Error details

* Entrypoint: Hekate 5.0.x
* System version: 5.0.2
* Checkpoint version: 3.1.0
* Expected behavior: Special characters in Switch profile username should be handled
* Encountered behavior: Special characters are replaced in dump folder name and the folder does not appear in the list
* Steps to reproduce:
  * step 1: Have a Switch profile username containing a special character ("Kévin" in my case)
  * step 2: Dump a game save for that profile
  * step 3: See the dump not appearing in the list and how the character is replaced in folder name (see below)

![screen](https://user-images.githubusercontent.com/1338139/40081765-48359b6a-588f-11e8-9477-dc53c14b07ca.PNG)

**Comment by DanSyor** [comment]
In my experience, the folder is even empty, which may be why it's not showing up.
Checkpoint issues a message on how "progress [was] correctly saved to disk" but there's nothing in the folder.

**Comment by Krarche** [comment]
Personally, the folder is not empty and I can see the different file writing to the SD card.
