### ISSUE TITLE
Unable to play Restored Save without restarting

### ISSUE THREAD

**Issue by Superx321** [BernardoGiordano/Checkpoint#83]
## Issue template

Please fill the fields with all the informations important for the maintainers to get your issue fixed or sorted out.

If you feel it's relevant, please attach screenshots or pictures that could detail the issue more.

* [ ] Issue with Checkpoint for 3DS
* [x] Issue with Checkpoint for Switch
* [ ] Feature request

### Error details

* Entrypoint:
* System version: 5.0.2
* Checkpoint version: 3.01
* Expected behaviour: Able to load a game with a loaded Save without restarting
* Encountered behavior: If i load/restore a Save and then open a Game for it, the game cant load. I have to restart my complete switch to be able to play that game. 
* Result code (if available):
* Steps to reproduce:
  * Start the Switch with a CFW, so i can open Checkpoint without restarting anymore
  * Play a Game
  * Close the Game
  * Open Checkpoint, scroll to the game, save the current state
  * Restore another save that you want to play on
  * Go back into the Main-Menu of the switch, start the Game
  * It wont load complete, stuck forever in loadingscreen

**Comment by BernardoGiordano** [comment]
This is the expected behaviour.
