### ISSUE TITLE
Saves with foreign characters do not show in app

### ISSUE THREAD

**Issue by thinktech2go** [BernardoGiordano/Checkpoint#84]
## Issue template

I can backup a save with foreign characters but if i goto load then they are not visible.

If you feel it's relevant, please attach screenshots or pictures that could detail the issue more.

* [ ] Issue with Checkpoint for 3DS
* [X] Issue with Checkpoint for Switch
* [ ] Feature request

 
### Feature request details

* I would like allow foreign characters to be viewable
* Because I can foresee this being a issue in foreign countries

**Comment by BernardoGiordano** [comment]
what do you mean with `I can backup a save with foreign characters but if i goto load then they are not visible.` ?

**Comment by thinktech2go** [comment]
so for instance I can backup this "20180514-203152 Rﾄｯﾄ耕"
but when I go to restore it doesn't even show on list of available backups
I would have to rename folder

On Sun, May 20, 2018 at 3:42 AM, Bernardo Giordano <notifications@github.com

**Comment by thinktech2go** [comment]
Never mind I saw you commit fixing this issue.

Thank you..

**Comment by BernardoGiordano** [comment]
Saves with foreign characters are still not supported, and I can do nothing about that because the path will not be recognized properly in the app if containing special characters.

**Comment by thinktech2go** [comment]
So it lists the save and if I don't name it when backup it will not list to
restore. However if I type a name it will show up in restore list.

Maybe have a way to auto rename when someone hits backup all. So that they
can restore later.

I'm assuming this could be a issue for people that have a different
language set on console with foreign keyboard.

Thanks

**Comment by BernardoGiordano** [comment]
Your username has foreign characters?

**Comment by yellows8** [comment]
"libnx bug" *Horizon OS

**Comment by thinktech2go** [comment]
​
