### ISSUE TITLE
[error report] Checkpoint freezing with NDS Pokemon Diamond cartridge

### ISSUE THREAD

**Issue by FM1337** [BernardoGiordano/Checkpoint#85]
# Error Report
### System
* [x] Issue with Checkpoint for 3DS
* [ ] Issue with Checkpoint for Switch

Error occurs on both the O2DS and the N2DS

### Error details

* Entrypoint: CIA installed app
* System version: 11.6.0
* Checkpoint version: 3.1.0
* Expected behaviour: Exporting and Importing save file to the Pokemon Diamond Cartridge should work
* Encountered behavior: Checkpoint freezes when attempting to export/import a save file and forces the system to have to be force shutdown by holding the power button for about 5-10 seconds.
* Result code (if available): N/A
* Steps to reproduce:
  * Insert Pokemon Diamond cartridge into 3DS/2DS
  * Load up checkpoint and wait for all the games to be loaded
  * Select the NDS cart game
  * Attempt to either import a save file or export a save file
### Other comments/additional information
We discussed this over discord and the conclusion that we had come to was the SPI functions that checkpoint is using doesn't know what to do with the cart. Also in previous versions, it would export a 0 byte save.

The cart was purchased on Amazon in December 2017 and while it doesn't appear to be a counterfeit from normal counterfeit signs, this behaviour from checkpoint (and other save apps) appear to suggest otherwise.

**Comment by BernardoGiordano** [comment]
Does this work? https://www.dropbox.com/s/joowr7w45mpaelx/Checkpoint.cia?dl=0

**Comment by FM1337** [comment]
No difference, still freezes
