### ISSUE TITLE
[Error: 00000E02] Trying to backup a save data

### ISSUE THREAD

**Issue by Ofdas23** [BernardoGiordano/Checkpoint#86]
Everytime I want to backup a save data (does not matter which game/application) I am getting this error: 
Error-Code: 00000E02
Failed to mount save

* [ ] Issue with Checkpoint for 3DS
* [X] Issue with Checkpoint for Switch
* [ ] Feature request

* Entrypoint: Fusee Gelee
* System version: 5.0.2
* Checkpoint version: v3.1.1 (also tested with v3.1.0, same issue)
* Expected behaviour: Backup save data from a game (in this case `Super Mario Odyssey`)
* Encountered behavior: Error-Code: 00000E02
* Steps to reproduce:
  * step 1: install Checkpoint v3.1.1/v3.1.0
  * step 2: launch RCM mode
  * step 3: use hekate 5.0
  * step 4: launch album application (--> Boots into hbmenu v2.0.0)
  * step 5: launch Checkpoint v3.1.1/v3.1.0
  * step 6: select a game (in this case `Super Mario Odyssey`)
  * step 7: press backup and then yes
  * step 8: error will show up (Error-Code: 00000E02, Failed to mount save)

**Comment by yellows8** [comment]
So you didn't do anything before running Album, after system-boot?

**Comment by Ofdas23** [comment]
After booting (using hekate 5.0) I connected my nintendo switch to the internet and then launched album (booting into hbmenu) but thats all. What should I do?

**Comment by yellows8** [comment]
That's fine.

**Comment by Ofdas23** [comment]
@yellows8 Oh okay..., but what is the issue? Why it does not work? Do you know it?

**Comment by yellows8** [comment]
dunno

**Comment by Ofdas23** [comment]
I just deleted everything related to checkpoint (checkpoint.nro/folders/...) and then installed checkpoint again and now it is working.
