### ISSUE TITLE
Checkpoint freezes while loading games list

### ISSUE THREAD

**Issue by Volcah** [BernardoGiordano/Checkpoint#87]
* [ ] Issue with Checkpoint for 3DS
* [x] Issue with Checkpoint for Switch
* [ ] Feature request

### Error details

* Entrypoint: Hekate 5.x
* System version: 5.0.2
* Checkpoint version: 3.1.0
* Expected behaviour: Load games list and backup saves
* Encountered behavior: Games list does not load properly and Checkpoint freezes before loading other games (and does not load some games because of the freeze)
* Result code (if available): 
* Steps to reproduce:
  * Launch RCM
  * Launch Hekate 5.x
  * Open Album app (HBL)
  * Run Checkpoint
 
I think it crashes because of Niconico, also I only have one copy of the other games while it displays more of them

![2018052322002902-db1426d1dfd034027cecde9c2dd914b8](https://user-images.githubusercontent.com/22454917/40448461-eb415406-5ed5-11e8-8241-dd5077f53c6e.jpg)

**Comment by BernardoGiordano** [comment]
Does this work instead? https://www.dropbox.com/s/63cuarl6jou2eh9/Checkpoint.nro?dl=0

**Comment by Volcah** [comment]
Yes it does, thanks!
