### ISSUE TITLE
does not show any save files for any of my games

### ISSUE THREAD

**Issue by 9efueifu** [BernardoGiordano/Checkpoint#89]
Im on 5.0.2 and checkpoint is not showing any save files that i have on my switch.
i put checkpoint in the switch folder on the sd card still not showing my save files

**Comment by BernardoGiordano** [comment]
can you give me a list of the games you have save files for?

**Comment by BernardoGiordano** [comment]
Anyways, can't reproduce. Give me more details otherwise I'll just close the issue.
