### ISSUE TITLE
Crash on load

### ISSUE THREAD

**Issue by CecilFF4** [BernardoGiordano/Checkpoint#9]
After loading about 40 titles or so (of 220 total), Checkpoint crashes. It does so consistently and at the same point every time. I systematically moved title data around so that it only had to load about 20 titles at a time: the crash never occurred, so this problem can't be narrowed down easily. When loading titles like this, ones that did not contain save data or contained unformatted save data did not show up, as expected; ones with saves did show up, and those saves could be backed up and restored just fine.

Ran another test where: I took out half the titles, ran Checkpoint, got no error, started putting titles back in, got error when I put back in "3D Classics Kid Icarus", took some other titles back out, error went away. So this isn't necessarily tied to any one game.

**Comment by BernardoGiordano** [comment]
This has already been fixed, #1.
