### ISSUE TITLE
Checkpoint not working with NS 5.1.0 firmware

### ISSUE THREAD

**Issue by eqwoot** [BernardoGiordano/Checkpoint#91]
Hi would there be an update for firmware 5.1.0 any soon?

* [X] Issue with Checkpoint for Switch
* System version: 5.1.0

**Comment by BernardoGiordano** [comment]
This is already fixed, wait for a new release to drop soon.

**Comment by eqwoot** [comment]
any ETA? thanks in advance!

**Comment by BernardoGiordano** [comment]
This does need more research.

**Comment by fennectech** [comment]
Anyone have a compiled build?  I cant compile because it cant find freetype2-config.  I need to restore a savegame ASAP

**Comment by BernardoGiordano** [comment]
I released a compiled build just yesterday.

**Comment by fennectech** [comment]
Its hanging.

**Comment by BernardoGiordano** [comment]
It's a homebrew launcher problem, not a Checkpoint problem.

**Comment by fennectech** [comment]
Im trying to bypass the homebrew launcher by renaming checkpoint to hbloader.nro and putting it on the root of the sdcard

**Comment by yellows8** [comment]
If it hangs before app displays: build yourself -> https://github.com/switchbrew/nx-hbloader

**Comment by fennectech** [comment]
Ive built and installed that.      It still hangs.

**Comment by yellows8** [comment]
What exactly hangs?

**Comment by fennectech** [comment]
I click the photos app and it hangs like the distributed version does.   This is the version im using  (my compiled version

**Comment by fennectech** [comment]
this is my built version.   ive included the checkpoint binary    it hangs when opening the photos app to get into hbmenu

[96AC-42CB.zip](https://github.com/BernardoGiordano/Checkpoint/files/2065308/96AC-42CB.zip)

**Comment by yellows8** [comment]
Again, where exactly does it hang?

**Comment by fennectech** [comment]
When you tap the photos app it tries to open the checkpoint app    it hangs on a blank home menu screen

**Comment by yellows8** [comment]
Offtopic for this repo then...

**Comment by fennectech** [comment]
wich repo should i open it in?

**Comment by fennectech** [comment]
https://github.com/switchbrew/nx-hbloader ?

**Comment by fennectech** [comment]
cold you link me to a recomended build enviroment?   ill set it up in a VM

**Comment by fennectech** [comment]
Owo   we use pacman  xD   im on an arch system lmao.

**Comment by fennectech** [comment]
ive followed the instructions on this page https://github.com/devkitPro/pacman/releases/tag/devkitpro-pacman-1.0.1   (skipping the installation of pacman ofc )

**Comment by BernardoGiordano** [comment]
He's not referring to the dev environment, but to the "hax" you're using on your console to run the homebrew menu.

**Comment by fennectech** [comment]
Ah   So wich enviroment should i use?
