### ISSUE TITLE
Terraria Extdata restore failed

### ISSUE THREAD

**Issue by michaelwilks216** [BernardoGiordano/Checkpoint#95]
## Issue template

Please fill the fields with all the informations important for the maintainers to get your issue fixed or sorted out.

If you feel it's relevant, please attach screenshots or pictures that could detail the issue more.

* [x] Issue with Checkpoint for 3DS
* [ ] Issue with Checkpoint for Switch
* [ ] Feature request

### Error details

* Entrypoint: cia
* System version: 11.6
* Checkpoint version: 3.2.0
* Expected behaviour: Successful Restore
* Encountered behavior: Failed Restore (attempting to transfer save from one 3ds to the other)
* Result code (if available): D8604665
* Steps to reproduce:
  * step 1: Backup Terraria Extdata on one 3DS
  * step 2: Transfer Data to another 3DS
  * step 3: Restore Extdata to second 3DS
  
### Feature request details

* I would like this feature...:
* Because...:

**Comment by BernardoGiordano** [comment]
That's an Out of resource error. Also, I can't reproduce. Are you sure the extdata for that game is initialized?

**Comment by michaelwilks216** [comment]
i'm pretty sure. on the 2nd 3DS i created a character then restored the data. i get that error.

**Comment by BernardoGiordano** [comment]
Can you test with this build? https://www.dropbox.com/s/yjqvcahj80fvubx/Checkpoint.cia?dl=0

**Comment by michaelwilks216** [comment]
Will do. My bad for taking a few days to reply. Got busy. ill download it tonight and test it tomorrow. ill let you know tomorrow if it works.

**Comment by michaelwilks216** [comment]
Tested that build on 4 3DS's got a Successful on all 4!
